# Generated by Django 5.1.2 on 2024-12-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('payments', '0002_remove_payment_appointment_payment_patient'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patient.patient'),
        ),
    ]
