# Generated by Django 5.1.2 on 2024-12-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_service_payment_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service_price',
        ),
    ]
