# Generated by Django 5.1.2 on 2024-12-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_service_price'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.services'),
        ),
    ]
