# Generated by Django 5.1.2 on 2024-12-20 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_service_payment_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='services',
        ),
    ]
