# Generated by Django 5.1.2 on 2024-12-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathological_process', models.TextField()),
                ('personal_history', models.TextField()),
                ('family_history', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('paraclinical_results', models.FileField(blank=True, null=True, upload_to='paraclinical_results/')),
                ('results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='appointments.appointment')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='payments.payment')),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='examinations', to='services.services')),
            ],
        ),
    ]
