# Generated by Django 5.1.2 on 2024-12-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medicalrecords', '0004_remove_medicalrecord_doctor_and_more'),
        ('payments', '0004_remove_payment_service_price'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='appointments.appointment')),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='medicalrecords.medicalrecord')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='payments.payment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='services.services')),
            ],
        ),
    ]
