# Generated by Django 5.1.2 on 2024-12-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='examination_price',
        ),
    ]
