# Generated by Django 5.1.2 on 2024-12-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medicalrecords', '0003_medicalrecord_doctor_medicalrecord_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
