# Generated by Django 5.1.2 on 2024-12-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_remove_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
    ]
