# Generated by Django 5.1.2 on 2024-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pathological_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='personal_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
